/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jorisaerts.omda.util;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class StringUtilsTest {
    @Test
    void testToPascalCase() {
        assertEquals("JorisAerts", StringUtils.toPascalCase("Joris Aerts"));
    }

    @Test
    void testToCamelCase() {
        assertEquals("jorisAerts", StringUtils.toCamelCase("Joris Aerts"));
    }
}
